project_id = "rkcyydydscmauguueuty"

[functions.ai-chat]
verify_jwt = true

[functions.translate]
verify_jwt = true

[functions.wikipedia-search]
verify_jwt = true

[functions.generate-image]
verify_jwt = true

[functions.analyze-file]
verify_jwt = true